# -*- coding: UTF-8 -*-
# Fortran 90 language definition file
#
# This file was taken from Andre Simon's fantastic
# syntax-highlighter "highlight" (www.andre-simon.de).

KW_LIST = {}
KW_RE = {}

IGNORECASE = False

STRINGDELIMITERS = "\" \'"

SL_COMMENT = "!"

KW_LIST['kwb'] = "INTEGER REAL DOUBLE PRECISION COMPLEX LOGICAL CHARACTER"

KW_LIST['kwa'] = '''ACCEPT ENDMAP PAUSE   ASSIGN ENDSTRUCTURE POINTER   AUTOMATIC ENDUNION PRINT   BACKSPACE ENTRY 
PROGRAM   BLOCKDATA EQUIVALENCE READ   BYTE EXTERNAL READONLY   CALL FIND REAL   CHARACTER FORMAT RECORD   
CLOSE FUNCTION RETURN   COMMON GOTO REWIND   COMPLEX IF REWRITE   CONTINUE IMPLICIT SAVE   DATA IMPLICITNONE 
SHARED   DECODE IMPLICITUNDEFINED STATIC   DEFINEFILE INCLUDE STOP   DELETE INQUIRE STRUCTURE   DIMENSION 
INTEGER SUBROUTINE   DO INTRINSIC THEN   DOUBLECOMPLEX KEY TO   DOUBLEPRECISION LOGICAL TYPE   ELSE MAP 
UNDEFINED   ELSEIF NAMELIST UNION   ENCODE NONE UNLOCK   END NOSPANBLOCKS VIRTUAL   ENDDO OPEN VOLATILE   
ENDFILE OPTIONS WHILE   ENDIF PARAMETER WRITE'''

SYMBOLS = "( ) [ ] { } , ; : & | < > - + = / * % + -"
